apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-tech-fast-food-app
  labels:
    app: fiap-tech-fast-food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-tech-fast-food-app
  template:
    metadata:
      name: fiap-tech-fast-food-app
      labels:
        app: fiap-tech-fast-food-app
    spec:
      containers:
        - name: fiap-tech-fast-food-container
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 600M
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          volumeMounts:
            - mountPath: "/mnt/secrets-store"
              name: secrets-store-inline
              readOnly: true
          env:
            - name: ATLAS_APP
              valueFrom:
                secretKeyRef:
                  name: fast-food-tech-challenge
                  key: ATLAS_APP
            - name: ATLAS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fast-food-tech-challenge
                  key: ATLAS_DB_HOST
            - name: ATLAS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: fast-food-tech-challenge
                  key: ATLAS_DB_USER
            - name: ATLAS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: fast-food-tech-challenge
                  key: ATLAS_DB_PASS

            - name: USER_POOL_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_POOL_ID
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CLIENT_ID
            - name: TOKEN_USE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TOKEN_USE
            - name: AUTHORIZATION_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTHORIZATION_URL
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: API_PORT
